

/*       LISTA DE FUNÇÕES DE ARRAYS 
  


HOJE MAL CONSEGUI ABRIR OS EXERCÍCIOS, CREIO QUE MEU RITMO SEJA MAIS LENTO MAS ESTOU FAZENDO TUDO NO MEU TEMPO E VEJO 
EVOLUÇÃO. COM A DEBANDADA ESTOU UM POUCO ASSUSTADO PORÉM SIGO CONFIANTE NO PROCESSO E VOU CONTINUAR TENTANDO, 
AS AULAS APARTIR DO FOR NÃO CONSEGUI PROCESSAR NADA AINDA, O CONTADOR ++ ÍNDICE, E TODO ESSE PROCESSAMENTO, PRECISO 
ESTUDAR MAIS MAS ESTOU NESSA JUSTAMENTE PELO TRABLHO REMOTO, E CADA VEZ MAIS ANIMADO EM APRENDER A PROGRAMAR PORQUE
É MUITO MASSA!!! É ISSO! 
PRETENDO IR REFAZENDO TODOS OS EXERCÍCIOS E DANDO UM NOVO COMMIT PRA ENVIAR COMPLETO E ORGANIZADO!

OBS: ESTOU DE MUDANÇA E PROTELEI UMA SEMANA DEVIDO A PROGRAMAÇÃO DO CURSO MAS DIA 13 JÁ ESTAREI EM OUTRA CIDADE,
MINHA COMPANHEIRA É TRANSFERIDA DE CIDADE CONSTANTEMENTE
 E PORQUE O GALO FOI CAMPEÃO BRASILEIRO
